services:
  bmecat-converter-app:
    build: .
    ports:
      - "5001:5001"
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:5001/health'
      interval: 10m
      timeout: 30s
      retries: 3
      start_period: 60s